void	initfsm(void);
void	drawfb(void);
void	resetfb(int);
void	initfb(void);
void	loadimg(void);
void	loadpics(void);
void	initfs(void);
int	max(int, int);
int	min(int, int);
void*	erealloc(void*, ulong, ulong);
void*	emalloc(ulong);
