void	enterloadmap(void);
void	enterintro(void);
int	advclock(void);
void	setfsm(void (*)(void), void (*)(Rune), int);
void	initfsm(void);
void	scrollpic(Pic*, int);
void	drawsubstr(int, int, char*, char*);
void	drawstr(int, int, char*);
void	drawrect(int, int, int, int, u32int);
void	drawpic(int, int, Pic*);
void	drawfill(u32int);
void	drawfb(void);
void	resetfb(int);
void	initfb(void);
void	loadimg(void);
void	loadpics(void);
void	initfs(void);
int	max(int, int);
int	min(int, int);
void*	erealloc(void*, ulong, ulong);
void*	emalloc(ulong);
